/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from RMUD3.Server.Gameplay.Creature */
export type Creature = {
    /** Transpiled from string */
    name: string;
}

/** Transpiled from RMUD3.Server.Gameplay.Player */
export type Player = {
    /** Transpiled from System.DateTime */
    lastPlayed: (Date | string);
} & Creature;

