/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from RMUD3.Server.Components.MainPageClientAction */
export enum MainPageClientAction {
    SignIn = 0,
    CreateAccount = 1,
}

/** Transpiled from RMUD3.Server.Components.MainPageServerAction */
export enum MainPageServerAction {
    SignInError = 0,
    CreateAccountError = 1,
}

