/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from RMUD3.Server.ServerComponents.MainPageClientAction */
export enum MainPageClientAction {
    MainPage = 0,
}

