/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from RMUD3.Server.Components.GamePage.SidebarData */
export type SidebarData = {
    /** Transpiled from string */
    playerName: string;
    /** Transpiled from string */
    locationName: string;
    /** Transpiled from string[] */
    creatures: string[];
}

/** Transpiled from RMUD3.Server.Components.GamePage.SidebarClientAction */
export enum SidebarClientAction {
    RequestUpdate = 0,
}

/** Transpiled from RMUD3.Server.Components.GamePage.SidebarServerAction */
export enum SidebarServerAction {
    Update = 0,
}

