/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import type { NewsItem } from './RMUD3.Server';

/** Transpiled from RMUD3.Server.Components.MainMenuEnableData */
export type MainMenuEnableData = {
    /** Transpiled from string */
    username: string;
    /** Transpiled from RMUD3.Server.NewsItem[] */
    news: NewsItem[];
    /** Transpiled from RMUD3.Server.Components.PlayerSummary[] */
    players: PlayerSummary[];
}

/** Transpiled from RMUD3.Server.Components.PlayerSummary */
export type PlayerSummary = {
    /** Transpiled from string */
    location: string;
    /** Transpiled from string */
    id: string;
    /** Transpiled from System.DateTime */
    lastPlayed: (Date | string);
}

/** Transpiled from RMUD3.Server.Components.MainMenuClientAction */
export enum MainMenuClientAction {
    NewGame = 0,
    LoadGame = 1,
}

/** Transpiled from RMUD3.Server.Components.SignInPageClientAction */
export enum SignInPageClientAction {
    SignIn = 0,
    CreateAccount = 1,
}

/** Transpiled from RMUD3.Server.Components.SignInPageServerAction */
export enum SignInPageServerAction {
    SignInError = 0,
    CreateAccountError = 1,
}

