/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from RMUD3.Server.NewsItem */
export type NewsItem = {
    /** Transpiled from string */
    title: string;
    /** Transpiled from System.DateTime */
    date: (Date | string);
    /** Transpiled from string */
    content: string;
}

