/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from RMUD3.Server.NewsItem */
export type NewsItem = {
    /** Transpiled from string */
    title: string;
    /** Transpiled from System.DateTime */
    date: (Date | string);
    /** Transpiled from string */
    content: string;
}

/** Transpiled from RMUD3.Server.Vector3 */
export type Vector3 = {
    /** Transpiled from float */
    x: number;
    /** Transpiled from float */
    y: number;
    /** Transpiled from float */
    z: number;
}

