/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import type { NewsItem } from './RMUD3.Server';

/** Transpiled from RMUD3.Server.Components.MainMenuPageComponent.MainMenuEnableData */
export type MainMenuEnableData = {
    /** Transpiled from string */
    username: string;
    /** Transpiled from RMUD3.Server.NewsItem[] */
    news: NewsItem[];
}

/** Transpiled from RMUD3.Server.Components.SignInPageClientAction */
export enum SignInPageClientAction {
    SignIn = 0,
    CreateAccount = 1,
}

/** Transpiled from RMUD3.Server.Components.SignInPageServerAction */
export enum SignInPageServerAction {
    SignInError = 0,
    CreateAccountError = 1,
}

